config/routes.rb
Rails.application.routes.draw do
  resources :posts
  resources :users
  
  root 'sessions#new' # ログイン画面のコントローラーとアクションを指定
  get 'login' => 'sessions#new', :as => :login
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy', as: :logout

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!
  has_many :posts, dependent: :destroy

  validates :last_name, presence: true, length: { maximum: 255 }
  validates :first_name, presence: true, length: { maximum: 255 }
  validates :email, presence: true, uniqueness: true
  validates :password, length: { minimum: 3 }
  validates :password, confirmation: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[show edit update destroy]

  # GET /posts
  def index
    @posts = Post.all
  end

  # GET /posts/1
  def show; end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit; end

  # POST /posts
  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id

    if @post.save
      redirect_to @post, notice: 'Post was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /posts/1
  def update
    if @post.update(post_params)
      redirect_to @post, notice: 'Post was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /posts/1
  def destroy
    @post.destroy
    redirect_to posts_url, notice: 'Post was successfully destroyed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def post_params
    params.require(:post).permit(:title, :content)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    # ログインフォームを表示するためのアクション
  end

  def create
    @user = login(params[:email], params[:password])
    if @user
      redirect_to posts_path, notice: 'Logged in successfully!'
    else
      flash.now[:alert] = 'Login failed'
      render action: 'new'
    end
  end

  def destroy
    logout
    redirect_to login_path, notice: 'Logged out!'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all # ユーザーの全てのレコードを取得します
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to login_path, notice: 'ユーザーが作成されました。ログインしてください。'
    else
      flash.now[:alert] = 'User registration failed. Please check your input.'
      render 'new'
    end
  end

  private

  def user_params
    params.require(:user).permit(:last_name, :first_name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PostAppSorcery</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <% if logged_in? %>
    <%= render partial: 'shared/header' %>
  <% else %>
    <%= render partial: 'shared/before_login_header' %>
  <% end %>
  
    <div class="container">
    <%= yield %>
    </div>

    <%= render 'shared/footer' %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Posts</h1>


<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

<tbody>
  <% @posts.each do |post| %>
    <tr>
      <td><%= post.title %></td>
      <td><%= post.content %></td>
      <td><%= link_to 'Show', post %></td>
      <% if post.user_id == current_user.id %>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tr>
  <% end %>
</tbody>

</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/shared/_before_login_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navigation navbar-light bg-light">

    <button class="navbar-toggler" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ml-auto main-nav align-items-center">
        <li class="nav-item">
          <%= link_to 'Login', login_path, class: 'nav-link' %>
        </li>
      </ul>
    </div>
  </nav>
</header>

app/views/shared/_flash_message.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/shared/_footer.html.erb
<footer id='footer' class="footer-bottom">
  <div class="container">
    <div class="row">
      <div class="col-sm-6 col-12">
        <div class="copyright">
          <p>Copyright © 2021. RUNTEQ</p>
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navigation navbar-light bg-light">

    <button class="navbar-toggler" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ml-auto main-nav align-items-center">
        <li class="nav-item dropdown dropdown-slide">
          <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Post
          </a>

          <div class="dropdown-menu dropdown-menu-right">
            <%= link_to 'List of Posts', posts_path, class: 'dropdown-item' %>
            <%= link_to 'New Post', new_post_path, class: 'dropdown-item' %>
          </div>
        </li>

        <li class="nav-item">
          <%= link_to 'List of Likes', '#', class: 'nav-link' %>
        </li>


<li class="nav-item dropdown dropdown-slide">
  <a href="#" class="nav-link" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" id="header-profile">
    <%= image_tag 'sample', size: '40x40', class: 'rounded-circle mr15'%>
  </a>
  <div class="dropdown-menu dropdown-menu-right">
    <div class="dropdown-item"><%= "#{current_user.last_name} #{current_user.first_name}" %></div>
    <div class="dropdown-divider"></div>
    <%= link_to 'Profile', '#', class: 'dropdown-item' %>
    <%= link_to 'Logout', logout_path, class: 'dropdown-item', method: :delete %>
  </div>
</li>

      </ul>
    </div>
  </nav>
</header>

app/views/users/index.html.erb
<h1>Users</h1>

<ul>
  <% @users.each do |user| %>
    <li><%= user.name %></li>
  <% end %>
</ul>

app/views/users/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10 offset-md-1 col-lg-8 offset-lg-2">
      <h1>New User</h1>
      <% if @user.errors.any? %>
        <div class="alert alert-danger">
          <ul>
            <% @user.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <%= form_with(model: @user, local: true) do |f| %>
        <div class="form-group">
          <%= f.label :last_name %>
          <%= f.text_field :last_name, class: 'form-control' %>
          <% if @user.errors.has_key?(:last_name) %>
            <p class="text-danger"><%= @user.errors[:last_name].first %></p>
          <% end %>
        </div>
        <div class="form-group">
          <%= f.label :first_name %>
          <%= f.text_field :first_name, class: 'form-control' %>
          <% if @user.errors.has_key?(:first_name) %>
            <p class="text-danger"><%= @user.errors[:first_name].first %></p>
          <% end %>
        </div>
        <div class="form-group">
          <%= f.label :email %>
          <%= f.text_field :email, class: 'form-control' %>
          <% if @user.errors.has_key?(:email) %>
            <p class="text-danger"><%= @user.errors[:email].first %></p>
          <% end %>
        </div>
        <div class="form-group">
          <%= f.label :password %>
          <%= f.password_field :password, class: 'form-control' %>
          <% if @user.errors.has_key?(:password) %>
            <p class="text-danger"><%= @user.errors[:password].first %></p>
          <% end %>
        </div>
        <div class="form-group">
          <%= f.label :password_confirmation %>
          <%= f.password_field :password_confirmation, class: 'form-control' %>
          <% if @user.errors.has_key?(:password_confirmation) %>
            <p class="text-danger"><%= @user.errors[:password_confirmation].first %></p>
          <% end %>
        </div>
        <%= f.submit "Create User", class: 'btn btn-primary' %>
      <% end %>
      <div class='text-center'>
        <a href="/login">Login</a>
      </div>
    </div>
  </div>
</div>